APP_NAME = "Mosaic"
EMPTY_STRING = ""
FILE_DATE_FORMAT = "%Y%m%d"
FILE_DATETIME_FORMAT = f"{FILE_DATE_FORMAT} %H%M%S"
LOGGING_FORMAT = '%(asctime)s %(levelname)s:%(message)s'
MAC_DS_STORE = '.DS_Store'
MARKDOWN_EXTENSION = '.md'
ALL_FILES = '*'
IMAGE_MIME_TYPE = "image"
APPLICATION_MIME_TYPE = "application"
PLAIN_TEXT_MIME_SUBTYPE = "text/plain"
JSON_MIME_SUBTYPE = f"{APPLICATION_MIME_TYPE}/json"
PDF_MIME_SUBTYPE = f"{APPLICATION_MIME_TYPE}/pdf"
MAC_OS = "Darwin"
UNIX_CR = "\n"

